version: "3.8"
services:
   buildroot-fosdem-build:
    build:
      context: ./
      args:
         BUILDROOT_USER: br-user
         BUILDROOT_DIR: buildroot
         BUILDROOT_VERSION: 2023.11.1
         # BUILDROOT_VERSION: git
         # BUILDROOT_BRANCH: master
         # Space deliminated list of external trees of which to use.
         EXTERNAL_TREES: fosdem
         BUILDROOT_PATCH_DIR: "fosdem/patches/buildroot/"
         UID: 1000
         GID: 1000
    environment:
      - APPLY_CONFIGS
      - CLEAN_AFTER_BUILD
      - ENV_FILES
      - EXIT_AFTER_BUILD
      - NO_BUILD
      - UPDATE_DCFC_PROGRAMS
      - VERBOSE
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - buildroot-fosdem-ccache:/home/ccache
    image: buildroot-fosdem-build:latest
    container_name:  buildroot-fosdem-build
volumes:
  buildroot-fosdem-ccache:
