################################################################################
#
# flutter-rfw-local-example
#
################################################################################

FLUTTER_RFW_LOCAL_EXAMPLE_VERSION = $(FLUTTER_PACKAGES_VERSION)
FLUTTER_RFW_LOCAL_EXAMPLE_SITE = $(FLUTTER_PACKAGES_SITE)
FLUTTER_RFW_LOCAL_EXAMPLE_SITE_METHOD = $(FLUTTER_PACKAGES_SITE_METHOD)
FLUTTER_RFW_LOCAL_EXAMPLE_SOURCE = $(FLUTTER_PACKAGES_SOURCE)
FLUTTER_RFW_LOCAL_EXAMPLE_LICENSE = $(FLUTTER_PACKAGES_LICENSE)
FLUTTER_RFW_LOCAL_EXAMPLE_LICENSE_FILES = $(FLUTTER_PACKAGES_LICENSE_FILES)
FLUTTER_RFW_LOCAL_EXAMPLE_DL_SUBDIR = $(FLUTTER_PACKAGES_DL_SUBDIR)
FLUTTER_RFW_LOCAL_EXAMPLE_SUBDIR= packages/rfw/example/local
FLUTTER_RFW_LOCAL_EXAMPLE_TARGET_INSTALL_DIR = $(TARGET_DIR)/usr/share/flutter/rfw-example/$(FLUTTER_ENGINE_RUNTIME_MODE)


$(eval $(flutter-package))
